server:
  port: ${SERVER_PORT:9090}
spring:
  application:
    name: prototype-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true
      routes:
        - id: auth-service
          uri: http://${AUTH_HOST:localhost}:${AUTH_PORT:8080}
          predicates:
            - Path=/auth-service/**
          filters:
            - RewritePath=/auth-service/(?<segment>.*), /${segment}
        - id: event-service
          uri: http://${EVENT_HOST:localhost}:${EVENT_PORT:8081}
          predicates:
            - Path=/event-service/**
          filters:
            - RewritePath=/event-service/(?<segment>.*), /${segment}
        - id: notification-service
          uri: http://${NOTIFICATION_HOST:localhost}:${NOTIFICATION_PORT:8082}
          predicates:
            - Path=/notification-service/**
          filters:
            - RewritePath=/notification-service/(?<segment>.*), /${segment}
        - id: product-service
          uri: http://${PRODUCT_HOST:localhost}:${PRODUCT_PORT:8083}
          predicates:
            - Path=/product-service/**
          filters:
            - RewritePath=/product-service/(?<segment>.*), /${segment}

url:
  bff-app: ${BFF_APP:http://localhost:3000}
  auth: ${AUTH_URL:http://localhost:8080}