spring:
  application:
    name: prototype-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      default-filters:
        - name: AuthGlobalFilter
          args:
            message: spring gateway auth filter
        - name: LoggingGlobalFilter
          args:
            message: spring gateway logging filter
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
            - Path=/auth-service/**
          filters:
            - RewritePath=/auth-service/(?<segment>.*), /${segment}
        - id: event-service
          uri: lb://event-service
          predicates:
            - Path=/event/**
            - Path=/event-service/**
          filters:
            - RewritePath=/event-service/(?<segment>.*), /${segment}
        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/notification/**
            - Path=/notification-service/**
          filters:
            - RewritePath=/notification-service/(?<segment>.*), /${segment}
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/product/**
            - Path=/product-service/**
          filters:
            - RewritePath=/product-service/(?<segment>.*), /${segment}

url:
  auth: ${AUTH_URL:http://localhost:8080}
